### ISSUE TITLE
HTTP 400 error reporting errors with long urls

### ISSUE THREAD

**Issue by PeterJCLaw** [keyerror/django-keyerror#11]
If an incoming request has a long url, such that `request.build_absolute_uri()` returns a string longer than 200 characters, we get an HTTP 400 error from KeyError's API.
It would be great if either there wasn't a limit (or it was considerably higher), or the urls were shortened to fit as needed.

**Comment by lamby** [comment]
This should now be fixed; thanks for the report. :)

**Comment by PeterJCLaw** [comment]
@lamby unfortunately we're still seeing HTTP 400s from this. The response body from a recent example is:
```
{"url": ["Ensure this value has at most 200 characters (it has 249)."]}
```

**Comment by lamby** [comment]
@PeterJCLaw wrote:

> unfortunately we're still seeing HTTP 400s from this.

Due to an SSL misconfiguration issue, the CI platform did not deploy this change despite me pushing the fix. I have now remedied this; thank you for checking. :)

**Comment by PeterJCLaw** [comment]
Aha, thanks for the quick response.
